### ISSUE TITLE
Video not buffering 

### ISSUE THREAD

**Issue by Gunak231** [luxysiv/revanced-nonroot#1]
Videos not buffering a minute. Tried without Google account sign in and after sign in

**Comment by luxysiv** [comment]
Install latest ReVanced GmsCore and
![Screenshot_2024-03-31-14-04-36-012_com brave browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/4de5cdd6-8cc7-462a-acad-780f705faa2c)
Like this
![Screenshot_2024-03-31-14-05-27-132_com miui powerkeeper](https://github.com/luxysiv/revanced-nonroot/assets/46205571/9898024b-f606-4953-af22-c70a9293b208)
