### ISSUE TITLE
why so big sized apk??

### ISSUE THREAD

**Issue by R-smth** [luxysiv/revanced-nonroot#10]
youtube rv is 142mb , can't it be splitted?

**Comment by luxysiv** [comment]
It's universal APK. You can split it by using j-hc/cli. 
You can fork this repository to do it

**Comment by luxysiv** [comment]
Revanced CLI not support split APK so we must be use j-hc/revanced-cli

**Comment by luxysiv** [comment]
I w

**Comment by luxysiv** [comment]
I will update my code to split 4 architectures

**Comment by luxysiv** [comment]
![Screenshot_2023-06-20-16-46-32-341_com lemurbrowser exts](https://github.com/luxysiv/revanced-nonroot/assets/46205571/9429f6b0-855d-450b-9424-3848b7ff893c)
