### ISSUE TITLE
Skip jobs/steps if patches are old "Old patch!!! Not build"

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#11]
Hello, can you added a step to skip jobs if patches are old (Old patch!!! Not build)
![Capture](https://github.com/luxysiv/revanced-nonroot/assets/118012196/e143eae2-4264-44e1-a322-16b36f59e5d0)

**Comment by luxysiv** [comment]
You can set exit 1 to do it,

**Comment by STEK1337** [comment]
Thank you
