### ISSUE TITLE
patching youtube revanced extended fails

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#12]
patch youtube revanced extended fails
![image](https://github.com/luxysiv/revanced-nonroot/assets/118012196/72003176-ba42-40e9-8b60-b5d282368844)

**Comment by luxysiv** [comment]
This issue belong to revanced-cli. Please wait inotia00 fix it

**Comment by STEK1337** [comment]
Patching works when I use CLI to patch youtube revanced extended

**Comment by luxysiv** [comment]
Did you patch on your PC?

**Comment by luxysiv** [comment]
Revanced Extended will drop in next week

**Comment by STEK1337** [comment]
yea, just saw it, I hope he will change his mind and continue working on revanced extended

**Comment by luxysiv** [comment]
I will use j-hc revanced-cli to fix it

**Comment by luxysiv** [comment]
Problem is download apk from APKmirror.  Please sync to fix

**Comment by luxysiv** [comment]
@STEK1337 You can fork manhduonghn/py-revanced-extended to build Revanced Extended with your logo. I was taken your options.toml and put in that repository. Thanks
