### ISSUE TITLE
Include mMicroG in releases

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#2]
Hello, I used your [mMicroG-patch.sh](https://github.com/luxysiv/mMicroG-patch/blob/main/mMicroG-patch.sh) and put it inside current revanced repository. This way it will release in the same repository, no need to use separate repository for microg, you can check it out here: https://github.com/STEK1337/youtube-extended/releases/tag/latest. If you like this idea feel free to implement it in your repository

**Comment by luxysiv** [comment]
Thanks,I will think about it

**Comment by luxysiv** [comment]
In new, you can use j-hc/revanced-cli to split apk
Example: gh_dl "inotia00" "revanced-patches revanced-integrations" "latest"
gh_dl "j-hc" "revanced-cli" "latest"
In function patch, you add $3 to split apk

**Comment by STEK1337** [comment]
Awesome, I implemented some of your changes into mine repository aswell. One last suggestion will be removing `revanced-extended-version.txt` and `revanced-version.txt` from releases. We already have link to latest patches in the changelog so we don't need these 2 files. This is entirely up to you. Have a gready day/night 😃

**Comment by luxysiv** [comment]
I like your fork, very well. And thanks for suggestions

**Comment by STEK1337** [comment]
Thanks, but you are the main star here, im just editing your stuff 😊

**Comment by luxysiv** [comment]
My code is so simply, and I read a lot repository on github to do it

**Comment by STEK1337** [comment]
That would be all from me for now at least, Im closing this issue form, have a great day 😃
