### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#3]
Is it possible to check for revanced extended patches update without using `revanced-extended-version.txt`

**Comment by luxysiv** [comment]
Yes, because you only build Revanced Extended so you can make Revanced patches ver into Changelog.md . So you will make a script to take version in Changelog and Revanced patches release and compare 2 version values

**Comment by luxysiv** [comment]
In my new, you no need change repository's name any more

**Comment by STEK1337** [comment]
Great, can you help me how to create Changelog.md script

**Comment by luxysiv** [comment]
What do you think about commit `revanced-extended-version.txt` to other branch and you git check out to compare 2 version

**Comment by STEK1337** [comment]
Ok, we can create a new branch called "update" but I dont have experience in creating git check to compare versions script. If you could help me with that in your free time I would appreciate it

**Comment by STEK1337** [comment]
Screenshot not opening

**Comment by STEK1337** [comment]
Maybe this will help

**Comment by luxysiv** [comment]
I tried but failure. So sorry. I still use release
