### ISSUE TITLE
Download and patch two architecture for youtube music [arm64-v8a & armeabi-v7a]

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#6]
Currently script is downloading only arm64-v8a, users with armeabi-v7a phones cannot install this apk, also include armeabi-v7a for patching

**Comment by luxysiv** [comment]
Uptodown source supported

**Comment by luxysiv** [comment]
I will update script to download armeabi-v7a APKmirror source

**Comment by luxysiv** [comment]
APKmirror updated

**Comment by luxysiv** [comment]
I try to write APKmirror, please wait

**Comment by luxysiv** [comment]
I rewrite to download armeabi-v7a on APKMirror, can you check?

**Comment by STEK1337** [comment]
I tried to build armeabi-v7a and arm64-v8a but it fails, or only one at a time get_apkmirror_ source can be enable? My request was to download both armeabi-v7a and arm64-v8a and patch, so in releases we will have `youtube-music-revanced-extended_armeabi-v7a.apk` and `youtube-music-revanced-extended_arm64-v8a.apk`

**Comment by luxysiv** [comment]
It can't because APKmirror only upload YTM arm64-v8a and armeabi-v7a not universal. I were test and script worked. Maybe uptodown support universal APK

**Comment by manhduonghn** [comment]
I updated can download arm64-v8a armeabi-v7a x86 and x86_64 select specific architecture

**Comment by luxysiv** [comment]
I updated can download arm64-v8a armeabi-v7a x86 and x86_64 specific architecture

**Comment by STEK1337** [comment]
Will test later because I'm on my phone right now.
Just to help you what im talking about
![Screenshot_20230522_035954_Chrome](https://github.com/luxysiv/revanced-nonroot/assets/118012196/f1793db2-82c9-4390-8437-95417b3f9d1c)

**Comment by luxysiv** [comment]
Ôh,You can try add in build-rv.sh or build-rve.sh . Example:
`get_patches_key "youtube-music-revanced-extended" 
 #get_apkmirror "youtube-music" "youtube-music" "google-inc/youtube-music/youtube-music" "arm64-v8a" 
 get_uptodown "youtube-music" "youtube-music"  
 patch "youtube-music" "youtube-music-revanced-extended-v$version-arm64-v8a"`
Only suggestion, It maybe work, I thinks

**Comment by luxysiv** [comment]
![Screenshot_2023-05-22-14-23-52-485_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/520e1dab-4d3e-4ab2-85ca-9f775c0e7a9b)

**Comment by luxysiv** [comment]
It works fine
![Screenshot_2023-05-22-14-48-42-094_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/12c0d046-88bb-4920-baa1-a9315092ede2)

![Screenshot_2023-05-22-14-49-04-432_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/99386520-d05d-4152-af1c-49de6685b73b)
![Screenshot_2023-05-22-14-49-18-515_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/98d3c35a-f065-49b6-a991-45d56b192f1e)

**Comment by luxysiv** [comment]
@STEK1337 
![Screenshot_2023-05-26-23-22-41-476_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/512f496a-8e76-40a4-954b-f844dd90e837)
