### ISSUE TITLE
Compression Levels

### ISSUE THREAD

**Issue by s-rs** [luxysiv/revanced-nonroot#9]
Adding compression levels to reduce apk sizes would be more convenient.

Thanks for your work

**Comment by luxysiv** [comment]
I think no need but I will think about it

**Comment by luxysiv** [comment]
I rewritten code. You can choose split apk out like arm64-v8a ,armeabi-v7a, x86 ,x87_64 and arm

**Comment by luxysiv** [comment]
What do you think about [this](https://github.com/manhduonghn/revanced-extended)

**Comment by luxysiv** [comment]
You can choose split apk out to arm64-v8a,armeabi-v7a,x86,x86_64 and arm

**Comment by subhashis-barad** [comment]
amazing..

**Comment by luxysiv** [comment]
Do you understand how it works?

**Comment by luxysiv** [comment]
Now I update code

**Comment by subhashis-barad** [comment]
> Do you understand how it works?

I am still new to this.

**Comment by manhduonghn** [comment]
> > Do you understand how it works?
> 
> I am still new to this.But it's such a great opportunity to learn from you and from your code I suppose by spliting the apk into only arm64-v8a this was made possible

It works. But if you want to split apk Revanced, you must be use this
`dl_gh "revanced" "revanced-patches revanced-integrations" "latest"
dl_gh "j-hc" "revanced-cli" latest`

**Comment by s-rs** [comment]
thanks bro,

**Comment by luxysiv** [comment]
You downloaded code from FiorenMas, who downloaded my code, and I was introduce she/he but she/he talk it's her/his code. So today I will make this feature : split 4 architectures to affirm I'm a creator. My code will be nice and uniformity. And I downloaded your index.html and renovated. Thanks
Waiting in a few minutes, I will update my code

**Comment by luxysiv** [comment]
![Screenshot_2023-06-20-16-46-32-341_com lemurbrowser exts](https://github.com/luxysiv/revanced-nonroot/assets/46205571/79fb96e4-700f-4270-b8a9-c4b8edc0110b)

**Comment by s-rs** [comment]
> You downloaded code from FiorenMas, who downloaded my code, and I was introduce she/he but she/he talk it's her/his code. So today I will make this feature : split 4 architectures to affirm I'm a creator. My code will be nice and uniformity. And I downloaded your index.html and renovated. Thanks Waiting in a few minutes, I will update my code

Ohh I thought it was his code. And I do it just for fun purposes and for myself only. If u have any issues I'll remove it immediately

**Comment by luxysiv** [comment]
I'm just telling you about the source of the code you downloaded.  It doesn't matter if he/she doesn't say it's 100% his/her code.  You see I took j-hc's ks.keystore and included him in contributors.  The apk download section also clearly states the reference source even though I have edited a lot.  I'm also clear in saying that I took your index.html.  The problem is FiorenMas, not you because you don't have the docs.  Sorry for making you misunderstand what I meant

**Comment by luxysiv** [comment]
![Screenshot_2023-06-21-12-47-21-985_org adblockplus browser](https://github.com/luxysiv/revanced-nonroot/assets/46205571/dea75927-789f-49b2-8b66-8abe2b107f0f)

**Comment by luxysiv** [comment]
His/her split apk feature is also guided by me.  Information to you

**Comment by s-rs** [comment]
> I'm just telling you about the source of the code you downloaded. It doesn't matter if he/she doesn't say it's 100% his/her code. You see I took j-hc's ks.keystore and included him in contributors. The apk download section also clearly states the reference source even though I have edited a lot. I'm also clear in saying that I took your index.html. The problem is FiorenMas, not you because you don't have the docs. Sorry for making you misunderstand what I meant

Ohh.. I misunderstood. Sorry from me too

**Comment by luxysiv** [comment]
I created another html different you. Thanks for your ideas
